version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - snowball

  mysql:
    container_name: mysql
    image: mysql:latest
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: Qkrwnstn012@
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: snowBall
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - "3306:3306"
    networks:
      - snowball
    volumes:
      - ./data:/var/lib/mysql


networks:
  snowball:
    driver: bridge
